const fs = require('fs');
const path = require('path');

const content = [
  "const express = require('express');",
  "const cors = require('cors');",
  "const jwt = require('jsonwebtoken');",
  "const bcrypt = require('bcrypt');",
  "const db = require('../db');",
  "require('dotenv').config();",
  "",
  "const app = express();",
  "",
  "app.use(cors({",
  "  origin: true,",
  "  methods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS'],",
  "  credentials: true",
  "}));",
  "",
  "app.use(express.json());",
  "",
  "const JWT_SECRET = process.env.JWT_SECRET || 'supersecretjwtkeyforticketing2026';",
  "",
  "const getNowJakarta = () => {",
  "  const now = new Date();",
  "  const jakartaStr = now.toLocaleString('sv-SE', { timeZone: 'Asia/Jakarta' });",
  "  return jakartaStr.slice(0, 16);",
  "};",
  "",
  "const authenticateToken = (req, res, next) => {",
  "  const authHeader = req.headers['authorization'];",
  "  const token = authHeader && authHeader.split(' ')[1];",
  "",
  "  if (!token) {",
  "    return res.status(401).json({ error: 'Akses ditolak. Token tidak ditemukan.' });",
  "  }",
  "",
  "  jwt.verify(token, JWT_SECRET, (err, user) => {",
  "    if (err) {",
  "      return res.status(403).json({ error: 'Sesi kedaluwarsa atau token tidak valid.' });",
  "    }",
  "    req.user = user;",
  "    next();",
  "  });",
  "};",
  "",
  "app.get('/api/health', (req, res) => {",
  "  res.json({ status: 'ok', time: new Date() });",
  "});",
  "",
  "app.post('/api/login', async (req, res) => {",
  "  const { username, password } = req.body;",
  "  if (!username || !password) {",
  "    return res.status(400).json({ error: 'Username dan password wajib diisi.' });",
  "  }",
  "",
  "  try {",
  "    const result = await db.query('SELECT * FROM users WHERE username = $1', [username]);",
  "    if (result.rows.length === 0) {",
  "      return res.status(401).json({ error: 'Kredensial tidak valid.' });",
  "    }",
  "",
  "    const dbUser = result.rows[0];",
  "    const isPasswordValid = await bcrypt.compare(password, dbUser.password_hash);",
  "    if (!isPasswordValid) {",
  "      return res.status(401).json({ error: 'Kredensial tidak valid.' });",
  "    }",
  "",
  "    const token = jwt.sign(",
  "      {",
  "        id: dbUser.id,",
  "        username: dbUser.username,",
  "        name: dbUser.name,",
  "        role: dbUser.role,",
  "        avatar: dbUser.avatar",
  "      },",
  "      JWT_SECRET,",
  "      { expiresIn: '8h' }",
  "    );",
  "",
  "    return res.json({",
  "      id: dbUser.id,",
  "      username: dbUser.username,",
  "      name: dbUser.name,",
  "      role: dbUser.role,",
  "      avatar: dbUser.avatar,",
  "      token",
  "    });",
  "  } catch (err) {",
  "    console.error('Login error:', err);",
  "    return res.status(500).json({ error: 'Terjadi kesalahan sistem saat login.' });",
  "  }",
  "});",
  "",
  "app.get('/api/users/me', authenticateToken, (req, res) => {",
  "  res.json(req.user);",
  "});",
  "",
  "app.get('/api/staff', async (req, res) => {",
  "  try {",
  '    const result = await db.query(\'SELECT id, username, name, role, avatar, completed_count AS "completedCount" FROM users ORDER BY completed_count DESC\');',
  "    res.json(result.rows);",
  "  } catch (err) {",
  "    console.error('Error fetching staff:', err);",
  "    res.status(500).json({ error: 'Gagal memuat daftar petugas.' });",
  "  }",
  "});",
  "",
  "app.get('/api/tickets', async (req, res) => {",
  "  try {",
  "    const result = await db.query('SELECT * FROM tickets ORDER BY id DESC');",
  "    res.json(result.rows);",
  "  } catch (err) {",
  "    console.error('Error fetching tickets:', err);",
  "    res.status(500).json({ error: 'Gagal memuat daftar tiket.' });",
  "  }",
  "});",
  "",
  "app.post('/api/tickets', async (req, res) => {",
  "  const { source, message } = req.body;",
  "  if (!source || !message) {",
  "    return res.status(400).json({ error: 'Sumber tiket dan pesan wajib diisi.' });",
  "  }",
  "",
  "  try {",
  "    const countResult = await db.query('SELECT COUNT(*) FROM tickets');",
  "    const totalTickets = parseInt(countResult.rows[0].count);",
  "    const ticketNum = 'TCK-2026-' + String(totalTickets + 101).padStart(3, '0');",
  "",
  "    const nowStr = getNowJakarta();",
  "",
  "    const result = await db.query(",
  "      `INSERT INTO tickets (ticket_number, source, message, status, created_at, updated_at)",
  "       VALUES ($1, $2, $3, 'belum_dikerjakan', $4, $5)",
  "       RETURNING *`,",
  "      [ticketNum, source, message, nowStr, nowStr]",
  "    );",
  "",
  "    res.status(201).json(result.rows[0]);",
  "  } catch (err) {",
  "    console.error('Error creating ticket:', err);",
  "    res.status(500).json({ error: 'Gagal membuat tiket baru.' });",
  "  }",
  "});",
  "",
  "app.patch('/api/tickets/:id', authenticateToken, async (req, res) => {",
  "  const { id } = req.params;",
  "  const { status } = req.body;",
  "",
  "  if (!status || !['belum_dikerjakan', 'diproses', 'selesai', 'ditolak'].includes(status)) {",
  "    return res.status(400).json({ error: 'Status tidak valid.' });",
  "  }",
  "",
  "  try {",
  "    const ticketCheck = await db.query('SELECT * FROM tickets WHERE id = $1', [id]);",
  "    if (ticketCheck.rows.length === 0) {",
  "      return res.status(404).json({ error: 'Tiket tidak ditemukan.' });",
  "    }",
  "",
  "    const isCompleted = status === 'selesai';",
  "    const isCancelled = status === 'ditolak';",
  "    const completedBy = isCompleted || isCancelled ? req.user.name : null;",
  "    const completedAt = isCompleted || isCancelled ? getNowJakarta() : null;",
  "    const updatedAt = getNowJakarta();",
  "",
  "    const updateResult = await db.query(",
  "      `UPDATE tickets",
  "       SET status = $1, completed_by = $2, completed_at = $3, updated_at = $4",
  "       WHERE id = $5",
  "       RETURNING *`,",
  "      [status, completedBy, completedAt, updatedAt, id]",
  "    );",
  "",
  "    res.json(updateResult.rows[0]);",
  "  } catch (err) {",
  "    console.error('Error updating ticket:', err);",
  "    res.status(500).json({ error: 'Gagal memperbarui status tiket.' });",
  "  }",
  "});",
  "",
  "module.exports = app;"
].join('\n');

fs.writeFileSync(path.join(__dirname, 'api', 'index.js'), content, 'utf8');
console.log('Done');
